### PR TITLE
Added Medi-App Poster Presentation document

### PR DESCRIPTION
**Pull request by mansiPaTeLL**
@holtzmak Please review the file. Thank you.

### CODE REVIEW

**Comment by mansiPaTeLL** [comment]
#22

**Comment by holtzmak** [comment]
My thoughts (I now see we need results section, don't remove - my bad. But I do notice that the box with results isn't the same gradient as the other boxes with text. Please change it to be gradient (even if it's a little bit!)
Comments
Additionally, your image is landscape orientation, the project outline says we need portrait orientation. Could you change this around?

**Comment by mansiPaTeLL** [comment]
@holtzmak I have completed the changes you requested. Please review the document. Thank you.

**Review by holtzmak — APPROVED** [review]
LGTM. Thank you for making the requested changes.

**Pull request merged**
